### ISSUE TITLE
run gives error at  data = read_data_sets(FLAGS.data_path, FLAGS.positive_label, FLAGS.percentage)

### ISSUE THREAD

**Issue by Sandy4321** [UCLA-StarAI/LogisticCircuit#1]
run gives error
File "e:\classifers\code\LogisticCircuit-master\LogisticCircuit-master\learn.py", line 73, in <module>
  main()
File "e:\classifers\code\LogisticCircuit-master\LogisticCircuit-master\learn.py", line 10, in main
  data = read_data_sets(FLAGS.data_path, FLAGS.positive_label, FLAGS.percentage)
File "e:\classifers\code\LogisticCircuit-master\LogisticCircuit-master\util\mnist_data.py", line 81, in read_data_sets
  train_image_file = maybe_download(train_image_file, train_dir)
File "e:\classifers\code\LogisticCircuit-master\LogisticCircuit-master\util\mnist_data.py", line 13, in maybe_download
  if not os.path.exists(work_directory):
File "C:\Users\sndr\Anaconda3\Lib\genericpath.py", line 19, in exists
  os.stat(path)

builtins.TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

![image](https://user-images.githubusercontent.com/11426119/53825094-7c2a0c80-3f43-11e9-8b7d-1d52940e9088.png)

**Comment by YitaoLiang** [comment]
Hi,
  Based on the error information, I suspect that you did not provide the path to the dataset in the command line.
  To show what you you need to provide, please type "python3 learn.py --help". Some of the arguments have default values and thus are optional. An example command that includes all required arguments is:
    python3 learn.py --data_path ./mnist_data --positive_label 0 --log_file ./log/mnist_label_0_log.txt --prediction_file ./prediction/mnist_label_0_prediction.txt

**Comment by Sandy4321** [comment]
I see
can you share where data can be taken and also did you check on usual classification data, not image data
if yes can you share some data to run code test?

**Comment by YitaoLiang** [comment]
We only tried on MNIST and Fashion. 
You can find MNIST on http://yann.lecun.com/exdb/mnist/
and Fashion on https://github.com/zalandoresearch/fashion-mnist
Our code is a general solution, so it definitely works on other datasets. The only thing you need to change is the vtree.

**Comment by YitaoLiang** [comment]
I also just uploaded a new script to "util/" that generates balanced vtrees for arbitrary datasets. Hope this would help.

**Comment by Sandy4321** [comment]
may you shear example from 0 to end for this kind of standard classification data
you can generate synthetic data

**Comment by YitaoLiang** [comment]
I didn't quite get you. What do you mean "example from 0 to end".
If you mean the examples with label 0 in the MNIST/Fashion dataset, the code base already handles that. The argument in your command line " --positive_label 0" would make the program search for all samples with label 0 in your training dataset, and treat them as the positive samples. 
If you want to extract those samples from the program, I guess the easiest way is to add one line of code right after "line 68" in "util/mnist_data.py" to save the positive images.

**Comment by Sandy4321** [comment]
I mean one pythopn file , what it is possible to run without any change and see how it works
usually, people add this kind of simple demo  , thanks

**Comment by YitaoLiang** [comment]
In some sense, MNIST and FASHION are the demos, right? They demonstrate logistic circuits are capable of achieving similar level of performance as deep learning. Definitely running on other datasets could be interesting as well, and we will consider doing that in the near future, but not right now. If you are interested in this, we highly encourage you to do so on your own, as we have already provided all the necessary scripts to facilitate this.  
I am going to close this issue, as what we are discussing  has largely deviated from the initial purpose of this issue.
If you have other suggestions or comments, I suggest we discuss though emails or you can create another issue that is directly about demos or other new features.
Thanks.
