### ISSUE TITLE
ConvergenceWarning: The max_iter was reached which means the coef_ did not converge

### ISSUE THREAD

**Issue by CarlaTeo** [UCLA-StarAI/LogisticCircuit#3]
I tried replicating the results with MNIST running with the following params:

` python3 learn.py --data_path /var/tmp/ --num_classes 10 --vtree balanced.vtree --circuit pretrained_models/mnist.circuit --num_structure_learning_iterations 100000`

Do I need to pre-proccess MNIST in some way? Should I increase even more the number of learning iterations? Or even something else?

Tks

**Comment by YitaoLiang** [comment]
If you are using the mnist_data.py in the util/ repo, the input data has been preprocessed.
If my memory is correct, this warning should be related to the parameter learning part. Usually you can simply ignore this, as more iterations only improve your performance by a very small amount.

**Comment by CarlaTeo** [comment]
Since after this warning appeared it looked like it was hanging I wasn't sure it was calculating or simply would never end. 
However after waiting a little bit more it indeed gave a result.

**Comment by YitaoLiang** [comment]
Yeah, the whole framework is very matrix computation intense. Sometimes, you just have to wait a bit. We are working on methods to speed up the whole thing. Once we have some interesting progress, we will update this repo.
