### ISSUE TITLE
the problem of program code

### ISSUE THREAD

**Issue by WANGrfy** [UCLA-StarAI/LogisticCircuit#4]
Hello, I am a graduate student of Northeast University of China. I have read the article "what to expect of classifiers? Reasoning about logistic regression with missing features" in recent days. I think the author's ideas and thoughts are very good. Later, I downloaded your code about this article on GitHub, and encountered some problems. I installed the required Python library. However, when running the program about MINST dataset, when the program runs to use "gpkit" to solve, there will be insufficient memory. My computer is 12gb of running memory. My initial idea is to reduce the dimension of data set, change the number of training samples from 60000 to 60, and the number of test sets from 10000 to 10. Use a small data set, but I find that the memory is still completely occupied. The program didn't finish running for eight hours. So I want to ask you, can your program run successfully? What system is your computer and how much memory? And if the number of samples is reduced, can it also operate normally? Will there be a memory overflow?
I'm sorry to disturb you. I hope you can answer for me. Thank you very much.

**Comment by YitaoLiang** [comment]
Hey, given we are discussing with you on another thread. I will close this issue here. We can continue our discussion there.
